-- MySQL Script generated by MySQL Workbench
-- Tue Nov 15 05:36:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hackathon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hackathon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hackathon` DEFAULT CHARACTER SET utf8mb4 ;
USE `hackathon` ;

-- -----------------------------------------------------
-- Table `hackathon`.`projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackathon`.`projet` (
  `idprojet` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(255) NULL,
  `Description` LONGTEXT NULL,
  `Image` VARCHAR(255) NULL,
  PRIMARY KEY (`idprojet`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackathon`.`votant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackathon`.`votant` (
  `idvotant` INT NOT NULL AUTO_INCREMENT,
  `NomPrenom` VARCHAR(255) NULL,
  `Tel` VARCHAR(45) NULL,
  `Email` VARCHAR(255) NULL,
  `motpass` VARCHAR(255) NULL,
  PRIMARY KEY (`idvotant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackathon`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackathon`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(255) NULL,
  `mdp` VARCHAR(255) NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackathon`.`vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackathon`.`vote` (
  `idvote` INT NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(45) NULL,
  `idprojet` INT NOT NULL,
  `idvotant` INT NOT NULL,
  PRIMARY KEY (`idvote`),
  INDEX `fk_vote_projet1_idx` (`idprojet` ASC),
  INDEX `fk_vote_votant1_idx` (`idvotant` ASC),
  CONSTRAINT `fk_vote_projet1`
    FOREIGN KEY (`idprojet`)
    REFERENCES `hackathon`.`projet` (`idprojet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vote_votant1`
    FOREIGN KEY (`idvotant`)
    REFERENCES `hackathon`.`votant` (`idvotant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
